apiVersion: v1
kind: Namespace
metadata:
  name: cnn-chile
  labels:
    name: cnn-chile
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnn-chile-dev
  labels:
    name: cnn-chile-dev
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
